{% set name = "filter_2col" %}
{% set version = "1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source: 
  path: ../src

requirements:
  host:
    - perl
  run:
    - perl

about:
  home: https://github.com/bidauxpoto/filter_2col
  summary: Bioinformatics and data analysis tool to filter a file based on the content of two different columns
